### ISSUE TITLE
Clarify location of source code

### ISSUE THREAD

**Issue by krystophny** [matrix-profile-foundation/joss_paper#1]
@vanbenschoten I have the point "Repository: Is the source code for this software available at the repository url?" on my reviewer checklist. It is not, since you created a separate repository for the paper only. Could you clarify how this should be handled for JOSS? It's my first review so I have no idea.

**Comment by tylerwmarrs** [comment]
@krystophny please see the message that arfon added. This paper is associated with three other libraries. I hope this helps. https://github.com/openjournals/joss-reviews/issues/2179#issuecomment-618374612

**Comment by tylerwmarrs** [comment]
@krystophny please see the message that arfon added. This paper is associated with three other libraries. I hope this helps. https://github.com/openjournals/joss-reviews/issues/2179#issuecomment-618374612

**Comment by krystophny** [comment]
@tylerwmarrs thanks, everything clear.

**Comment by tylerwmarrs** [comment]
@krystophny - For clarity, I linked the libraries mentioned in the paper directly to their respective GitHub repositories.
