### ISSUE TITLE
Contribution and authorship

### ISSUE THREAD

**Issue by krystophny** [matrix-profile-foundation/joss_paper#2]
@vanbenschoten I see only a single commit from you in the three repositories for this paper:

* https://github.com/matrix-profile-foundation/tsmp (mainly @franzbischoff )
* https://github.com/matrix-profile-foundation/go-matrixprofile (mainly @aouyang1 )
* https://github.com/matrix-profile-foundation/matrixprofile (mainly @tylerwmarrs , some @nikita-smyrnov )

Please clarify your contribution as the main author.

**Comment by vanbenschoten** [comment]
@krystophny Definitely! My role has primarily been that of the Primary Investigator/Corresponding Author. We decided to list names alphabetically given that we see all of our contributions as equal, but I'm also happy to list my name in the more traditional corresponding author spot at the end.

1) I'm the head of the Matrix Profile Foundation and brought this great group of folks together to form the MPF body & vision.

2) I'm the original author of the first Python implementation of Matrix Profile (https://github.com/target/matrixprofile-ts), which helped shape our viewpoint into how the libraries should be designed and evolve. 

2) I was heavily involved in architecting the Matrix Profile API itself.

3) I'm the author of the JOSS paper

**Comment by krystophny** [comment]
@vanbenschoten thanks for the info. Just one more question: why not include https://github.com/target/matrixprofile-ts in the submission? Has this already been published elsewhere, or what's the reason not to include it?

**Comment by vanbenschoten** [comment]
@krystophny We didn't include matrixprofile-ts because Target (who still owns the GitHub repo) decided they didn't want the codebase to be part of the broader body of MPF work.

**Comment by krystophny** [comment]
Alright. Based on this information I can conclude that besides formulating the paper you did major conceptual developments and wrote the paper, while your original Python code is not part of the contribution for organizational reasons. It has however been used as a template for the other codes. This should justify your authorship.
